
name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - env:
        jira.email.address: ${{ JIRA_EMAIL_ADDRESS }}
        jira.api.key: ${{ JIRA_API_KEY }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: '5.0'
    - name: Build with Maven
      run: mvn -B test --file backend/pom.xml
